variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

before_script:
  - export PROJECT_VERSION_MAJOR_MINOR=`cat VERSION`
  - export VERSION=`greycat build-version`

build:
  stage: build
  tags: [ linux ]
  script:
    - greycat install
    - GREYCAT_CORE=1 bin/greycat codegen python
    - ./build.sh
  artifacts:
    when: on_success
    expire_in: '30 days'
    paths:
      - dist

publish:
  stage: publish
  tags: [ linux ]
  when: manual
  script:
    - ./publish.sh
  artifacts:
    expire_in: 1 week
    paths:
      - dist
