image: oci.datathings.com/greycat/build/python:1.0.1-main

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

before_script:
  - export VERSION=`git2version -s`

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    when: on_success
    expire_in: '30 days'
    paths:
      - dist

publish:
  stage: publish
  when: manual
  script:
    - ./publish.sh
  artifacts:
    expire_in: 1 week
    paths:
      - dist
