[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "greycat"
version = "0.0.0"
readme = "README.md"

[tool.poetry]
name=""
version = "0.0.0"
readme = "README.md"
description = ""
authors = []