[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "greycat"
version = "0.0.0"
authors = [
  { name="Example Author", email="author@example.com" },
]
readme = "README.md"
requires-python = ">=3.8"